name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  release:
    types: [ published ]

jobs:
  build-amd:
    runs-on: "buildjet-4vcpu-ubuntu-2204"

    steps:
    - uses: actions/checkout@v3
    - name: Build and publish a Docker image for ${{ github.repository }}
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}  # it will be lowercased internally
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build-arm:
    runs-on: "buildjet-4vcpu-ubuntu-2204-arm"

    steps:
    - uses: actions/checkout@v3
    - name: Build and publish a Docker image for ${{ github.repository }}
      uses: macbre/push-to-ghcr@master
      with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}