name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  release:
    types: [ published ]

jobs:
  build-amd:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
        - uses: actions/checkout@v3
        - uses: docker/setup-buildx-action@v2
        - name: Login to GHCR
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v1
          with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            platforms: linux/amd64
            push: true
            tags: ghcr.io/bennjii/open-pos:latest

  build-arm:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
        - uses: actions/checkout@v3
        - uses: docker/setup-buildx-action@v2
        - name: Login to GHCR
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            platforms: linux/arm64
            push: true
            tags: ghcr.io/bennjii/open-pos:latest-arm